language: bash

script:
	# Download the latest version of the Mend Unified Agent
    - curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
	# Download the default configuration file
    - curl -LJO https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss-unified-agent.config
	# Replace the flags in the configuration to enable policy check
    - cat wss-unified-agent.config | sed -e "s/checkPolicies=false/checkPolicies=true/; s/forceCheckAllDependencies=false/forceCheckAllDependencies=true/" > temp_file.config
	# Copy the new configuration file over the original file
    - mv temp_file.config wss-unified-agent.config
	# Run whitesource FS Agent
    - java -jar wss-unified-agent.jar -apiKey xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx -c wss-unified-agent.config -d ~/ -project travisCI_test
    
  


  
  

  
  
  
  
  
  
  
  

